name: Latest blog post workflow
on:
  schedule:
  - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "4"
          feed_list: "https://www.yodabi.com/feed/"
          user_agent: "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
